Organisasjonsnummer	Navn	Organisasjonsform.kode	Organisasjonsform.beskrivelse	Næringskode 1	Næringskode 1.beskrivelse	Næringskode 2	Næringskode 2.beskrivelse	Næringskode 3	Næringskode 3.beskrivelse	Hjelpeenhetskode	Hjelpeenhetskode.beskrivelse	Antall ansatte	Hjemmeside	Postadresse.adresse	Postadresse.poststed	Postadresse.postnummer	Postadresse.kommune	Postadresse.kommunenummer	Postadresse.land	Postadresse.landkode	Forretningsadresse.adresse	Forretningsadresse.poststed	Forretningsadresse.postnummer	Forretningsadresse.kommune	Forretningsadresse.kommunenummer	Forretningsadresse.land	Forretningsadresse.landkode	Institusjonell sektorkode	Institusjonell sektorkode.beskrivelse	Siste innsendte årsregnskap	Registreringsdato i Enhetsregisteret	Stiftelsesdato	FrivilligRegistrertIMvaregisteret	Registrert i MVA-registeret	Registrert i Frivillighetsregisteret	Registrert i Foretaksregisteret	Registrert i Stiftelsesregisteret	Konkurs	Under avvikling	Under tvangsavvikling eller tvangsoppløsning	Overordnet enhet i offentlig sektor	Målform


922924368	- A THOUSAND WORDS - ØDEGÅRDEN GJERRUD TRANSLATIONS	ENK	Enkeltpersonforetak	74.300	Oversettelses- og tolkevirksomhet							0									Storgaten 120	SVELVIK	3060	DRAMMEN	3005	Norge	NO	8200	Personlig næringsdrivende		2019-06-19			JA	NEI	NEI	NEI	NEI	NEI	NEI		Bokmål



Organisasjonsnummer,
Navn,
Organisasjonsform.kode,
Organisasjonsform.beskrivelse,
Næringskode 1,
Næringskode 1.beskrivelse,
Næringskode 2,
Næringskode 2.beskrivelse,
Næringskode 3,
Næringskode 3.beskrivelse,
Hjelpeenhetskode,
Hjelpeenhetskode.beskrivelse,
Antall ansatte,
Hjemmeside,
Postadresse.adresse,
Postadresse.poststed,
Postadresse.postnummer,
Postadresse.kommune,
Postadresse.kommunenummer,
Postadresse.land,
Postadresse.landkode,
Forretningsadresse.adresse,
Forretningsadresse.poststed,
Forretningsadresse.postnummer,
Forretningsadresse.kommune,
Forretningsadresse.kommunenummer,
Forretningsadresse.land,
Forretningsadresse.landkode,
Institusjonell sektorkode,
Institusjonell sektorkode.beskrivelse,
Siste innsendte årsregnskap,
Registreringsdato i Enhetsregisteret,
Stiftelsesdato,
FrivilligRegistrertIMvaregisteret,
Registrert i MVA-registeret,
Registrert i Frivillighetsregisteret,
Registrert i Foretaksregisteret,
Registrert i Stiftelsesregisteret,
Konkurs,
Under avvikling,
Under tvangsavvikling eller tvangsoppløsning,
Overordnet enhet i offentlig sektor,
Målform,


922924368,
- A THOUSAND WORDS - ØDEGÅRDEN GJERRUD TRANSLATIONS,
ENK,
Enkeltpersonforetak,
74.300,
Oversettelses- og tolkevirksomhet,
,
,
,
,
,
,
0,
,
,
,
,
,
,
,
,
Storgaten 120,
SVELVIK,
3060,
DRAMMEN,
3005,
Norge,
NO,
8200,
Personlig næringsdrivende,
,
2019-06-19,
,
,
JA,
NEI,
NEI,
NEI,
NEI,
NEI,
NEI,
,
Bokmål


'Organisasjonsnummer',
'Navn',
'Organisasjonsform.kode',
'Organisasjonsform.beskrivelse',
'Næringskode 1',
'Næringskode 1.beskrivelse',
'Næringskode 2',
'Næringskode 2.beskrivelse',
'Næringskode 3',
'Næringskode 3.beskrivelse',
'Hjelpeenhetskode',
'Hjelpeenhetskode.beskrivelse',
'Antall ansatte',
'Hjemmeside',
'Postadresse.adresse',
'Postadresse.poststed',
'Postadresse.postnummer',
'Postadresse.kommune',
'Postadresse.kommunenummer',
'Postadresse.land',
'Postadresse.landkode',
'Forretningsadresse.adresse',
'Forretningsadresse.poststed',
'Forretningsadresse.postnummer',
'Forretningsadresse.kommune',
'Forretningsadresse.kommunenummer',
'Forretningsadresse.land',
'Forretningsadresse.landkode',
'Institusjonell sektorkode',
'Institusjonell sektorkode.beskrivelse',
'Siste innsendte årsregnskap',
'Registreringsdato i Enhetsregisteret',
'Stiftelsesdato',
'FrivilligRegistrertIMvaregisteret',
'Registrert i MVA-registeret',
'Registrert i Frivillighetsregisteret',
'Registrert i Foretaksregisteret',
'Registrert i Stiftelsesregisteret',
'Konkurs',
'Under avvikling',
'Under tvangsavvikling eller tvangsoppløsning',
'Overordnet enhet i offentlig sektor',
'Målform',


'922924368',
'- A THOUSAND WORDS - ØDEGÅRDEN GJERRUD TRANSLATIONS',
'ENK',
'Enkeltpersonforetak',
'74.300',
'Oversettelses- og tolkevirksomhet',
'',
'',
'',
'',
'',
'',
'0',
'',
'',
'',
'',
'',
'',
'',
'',
'Storgaten 120',
'SVELVIK',
'3060',
'DRAMMEN',
'3005',
'Norge',
'NO',
'8200',
'Personlig næringsdrivende',
'',
'2019-06-19',
'',
'',
'JA',
'NEI',
'NEI',
'NEI',
'NEI',
'NEI',
'NEI',
'',
'Bokmål',