setx POSTGRES_USER mediavest /m
setx POSTGRES_PASSWORD "F%K6L51KXGXs" /m
setx POSTGRES_SERVER prospector-user-api.cpjevlwuwfix.eu-west-2.rds.amazonaws.com /m
setx POSTGRES_PORT 5432 /m
setx POSTGRES_DB ProSpector_User_API /m
setx SECRET_KEY NO_SECRET_KEY /m
setx USE_SQLITE_DB False /m
setx MAIL_FROM prospector.feedback@gmail.com /m
setx MAIL_PORT 587 /m
setx MAIL_SERVER smtp.gmail.com /m
setx MAIL_FROM_NAME ProSpector /m
setx MAIL_USERNAME prospector.feedback@gmail.com /m
setx MAIL_PASSWORD udrpwxglgjbspweo /m
setx MAIL_TSL True /m
setx MAIL_SSL False /m
setx USE_CREDENTIALS True /m
setx TWILIO_ACCOUNT_SID AC2c22cfe2b414f1941eefb50c5a1649e5 /m
setx TWILIO_AUTH_TOKEN 4b0e4a07643383388f2b031f91366ef2 /m